apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: webhookie-services
  name: admin-service
  labels:
    release: webhookie-prometheus # This name must match 'Prometheus Operator' release name!!!
    app.kubernetes.io/component: webhookie-metrics
    app.kubernetes.io/instance: webhookie-services
    app.kubernetes.io/managed-by: services
    app.kubernetes.io/name: admin-service-metrics
    app.kubernetes.io/part-of: services-metrics
spec:
  selector:
    matchLabels:
      app: admin-service
  endpoints:
    - port: http-traffic
      path: "/manage/prometheus"
