apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: datasource-config
  files:
  - data/grafana-datasource.yml
  options:
    disableNameSuffixHash: true
#- name: jvm-dashboard-config
#  files:
#  - "./data/JVM (Micrometer)-dashboard 4701.json"
#  options:
#    disableNameSuffixHash: true
#- name: spring-dashboard-config
#  files:
#  - "./data/SpringBoot APM Dashboard-12900.json"
#  options:
#    disableNameSuffixHash: true
resources:
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

