apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webhookie-grafana
  name: webhookie-grafana
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: webhookie-grafana
  type: ClusterIP
status:
  loadBalancer: {}
