apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: asyncapi-parser
  name: asyncapi-parser
spec:
  ports:
  - name: http-traffic
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: asyncapi-parser
  type: ClusterIP
status:
  loadBalancer: {}
