apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: definitions-config
  files:
  - definitions.json
  options:
    disableNameSuffixHash: true
resources:
  - definition.yaml

namePrefix: webhookie-

