apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: portal
  name: portal
spec:
  ports:
  - name: http-traffic
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: portal
  type: ClusterIP
status:
  loadBalancer: {}
