version: '3.9'

x-services-small-env:
  &services-small-env
  JAVA_TOOL_OPTIONS: "-Xms${SMALL_MS_MEM}M -Xmx${SMALL_MX_MEM}M"

x-services-small:
  &services-small
  limits:
    cpus: "${SMALL_CPU_LIMIT}"
    memory: "${SMALL_MX_MEM}M"
  reservations:
    cpus: "${SMALL_CPU_RES}"
    memory: "${SMALL_MS_MEM}M"

services:
  registry-service:
    container_name: registry-service
    image: hookiesolutions/webhookie-registry-service:${WEBHOOKIE_TAG}
    ports:
      - "8761:8761"
    networks:
      webhookie:
    deploy:
      resources:
        *services-small
    environment:
      <<: *services-small-env
