version: '3.9'

services:
  webhookie-amqp:
    restart: always
    image: rabbitmq:3.10.2-management
    hostname: webhookie-amqp
    stdin_open: true
    tty: true
    ports:
      - "0.0.0.0:5672:5672/tcp"
      - "0.0.0.0:15672:15672/tcp"
    volumes:
      - ./data/rabbit/webhookie-rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./data/rabbit/webhookie-rabbit-definitions.json:/etc/rabbitmq/definitions.json
    networks:
      webhookie:
