apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: http-publisher
  name: http-publisher
spec:
  ports:
  - name: http-traffic
    port: 8084
    protocol: TCP
    targetPort: 8080
  selector:
    app: http-publisher
  type: ClusterIP
status:
  loadBalancer: {}
