apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: prometheus-config
  files:
  - data/prometheus.yml
  options:
    disableNameSuffixHash: true
resources:
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

