apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "5.0.9"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: webhookie-user
      db: wh-admin-db
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: webhookie-mongodb-password
      roles:
        - db: "wh-admin-db"
          name: "dbOwner"
        - db: "wh-admin-db"
          name: "clusterAdmin"
        - db: "wh-admin-db"
          name: "userAdminAnyDatabase"
      scramCredentialsSecretName: webhookie-scram
    - name: webhookie-user
      db: wh-subscription-db
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: webhookie-mongodb-password
      roles:
        - db: "wh-subscription-db"
          name: "dbOwner"
        - db: "wh-subscription-db"
          name: "clusterAdmin"
        - db: "wh-subscription-db"
          name: "userAdminAnyDatabase"
      scramCredentialsSecretName: webhookie-scram
    - name: webhookie-user
      db: wh-traffic-db
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: webhookie-mongodb-password
      roles:
        - db: "wh-traffic-db"
          name: "dbOwner"
        - db: "wh-traffic-db"
          name: "clusterAdmin"
        - db: "wh-traffic-db"
          name: "userAdminAnyDatabase"
      scramCredentialsSecretName: webhookie-scram
    - name: webhookie-user
      db: wh-webhookapi-db
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: webhookie-mongodb-password
      roles:
        - db: "wh-webhookapi-db"
          name: "dbOwner"
        - db: "wh-webhookapi-db"
          name: "clusterAdmin"
        - db: "wh-webhookapi-db"
          name: "userAdminAnyDatabase"
      scramCredentialsSecretName: webhookie-scram
    - name: webhookie-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: webhookie-mongodb-password
      roles:
        - db: "admin"
          name: "clusterAdmin"
        - db: "admin"
          name: "userAdminAnyDatabase"
        - db: "admin"
          name: "readWrite"
        - db: "admin"
          name: "readWriteAnyDatabase"
      scramCredentialsSecretName: webhookie-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
