apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: discovery-cluster-role

rules:
  - apiGroups: [""]
    resources: ["nodes", "services", "pods", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]

---

apiVersion: v1
kind: ServiceAccount

metadata:
  name: webhookie-service-account
  namespace: webhookie-services

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: webhookie-cluster-role-binding

roleRef:
  kind: ClusterRole
  name: webhookie-cluster-role
  apiGroup: rbac.authorization.k8s.io

subjects:
  - kind: ServiceAccount
    name: webhookie-service-account
    namespace: default
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: webhookie-services
  name: namespace-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: webhookie-services
subjects:
  - kind: ServiceAccount
    name: webhookie-service-account
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
