apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-ingress
    log-label: "true"
  name: api-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-ingress
  strategy: {}
  template:
    metadata:
      labels:
        app: api-ingress
        log-label: "true"
    spec:
      containers:
      - image: hookiesolutions/webhookie-api-ingress
        name: api-ingress
        resources: {}
        env:
          - name: SPRING_CONFIG_IMPORT
            value: "file:/var/app/data/auth.yml"
        envFrom:
          - secretRef:
              name: auth-env
          - secretRef:
              name: rabbitmq-env
          - secretRef:
              name: k8s-env
        volumeMounts:
          - name: auth-yml-volume
            mountPath: var/app/data/auth.yml
            subPath: auth.yml
#        livenessProbe:
#          httpGet:
#            path: /alive
#            port: 8080
#          initialDelaySeconds: 15
#          timeoutSeconds: 60
#          periodSeconds: 15
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          httpGet:
            path: /manage/health/readiness
            port: 8080
      volumes:
        - name: auth-yml-volume
          configMap:
            name: auth-yml # Name of the ConfigMap which contains definitions you wish to import
            items:
              - key: auth.yml
                path: auth.yml
      serviceAccountName: webhookie-service-account
