apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-gateway
  name: api-gateway
spec:
  ports:
  - name: http-traffic
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-gateway
  type: ClusterIP
status:
  loadBalancer: {}
