apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: webhookie-elasticsearch
spec:
  version: 8.4.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      # PROD config
#      podTemplate:
#        spec:
#          initContainers:
#            - name: sysctl
#              securityContext:
#                privileged: true
#                runAsUser: 0
#              command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
      # REMOVE for PROD
#      config:
#        node.store.allow_mmap: false
