apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webhookapi-repo
  name: webhookapi-repo
spec:
  ports:
  - name: http-traffic
    port: 8088
    protocol: TCP
    targetPort: 8080
  selector:
    app: webhookapi-repo
  type: ClusterIP
status:
  loadBalancer: {}
