apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: webhookie-traffic-mongodb-secret
    literals:
      - connectionString.standardSrv=mongodb://webhookie-user:passwd@webhookie-mongodb-svc.webhookie-mongodb.svc.cluster.local/wh-traffic-db?replicaSet=webhookie-mongodb&ssl=false
resources:
  - deployment.yaml
  - service.yaml
#  - service-monitor.yaml
