apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: webhookie-services
  name: traffic-service
  labels:
    release: webhookie-prometheus # This name must match 'Prometheus Operator' release name!!!
spec:
  selector:
    matchLabels:
      app: traffic-service
  endpoints:
    - port: http-traffic
      path: "/manage/prometheus"
