apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: traffic-service
  name: traffic-service
spec:
  ports:
  - name: http-traffic
    port: 8087
    protocol: TCP
    targetPort: 8080
  selector:
    app: traffic-service
  type: ClusterIP
status:
  loadBalancer: {}
