apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    log-label: "true"
    app: hmac-signer
  name: hmac-signer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hmac-signer
  strategy: {}
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs.json-logging/json.keys_under_root: "true"
        co.elastic.logs.json-logging/json.add_error_key: "true"
        co.elastic.logs.json-logging/json.message_key: "message"
      labels:
        log-label: "true"
        app: hmac-signer
    spec:
      containers:
      - image: hookiesolutions/webhookie-hmac-signer
        name: hmac-signer
        resources: {}
        env:
          - name: SPRING_CONFIG_IMPORT
            value: "file:/var/app/data/auth.yml"
        envFrom:
          - secretRef:
              name: auth-env
          - secretRef:
              name: rabbitmq-env
          - secretRef:
              name: crypto-key-env
          - secretRef:
              name: k8s-env
        volumeMounts:
          - name: auth-yml-volume
            mountPath: var/app/data/auth.yml
            subPath: auth.yml
#        livenessProbe:
#          httpGet:
#            path: /alive
#            port: 8080
#          initialDelaySeconds: 15
#          timeoutSeconds: 5
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          httpGet:
            path: /manage/health/readiness
            port: 8080
      volumes:
        - name: auth-yml-volume
          configMap:
            name: auth-yml # Name of the ConfigMap which contains definitions you wish to import
            items:
              - key: auth.yml
                path: auth.yml
      serviceAccountName: webhookie-service-account
