apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: oauth2-signer
  name: oauth2-signer
spec:
  ports:
  - name: http-traffic
    port: 8090
    protocol: TCP
    targetPort: 8080
  selector:
    app: oauth2-signer
  type: ClusterIP
status:
  loadBalancer: {}
