apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhookie-filebeat
subjects:
  - kind: ServiceAccount
    name: webhookie-filebeat
    namespace: webhookie-logging
roleRef:
  kind: ClusterRole
  name: webhookie-filebeat
  apiGroup: rbac.authorization.k8s.io
