apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webhookie-filebeat
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
